ALTER TABLE "Invitation"
  ADD COLUMN IF NOT EXISTS "isEnabled" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Invitation"
  ADD COLUMN IF NOT EXISTS "note" TEXT;

ALTER TABLE "Invitation"
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Invitation"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "Invitation_isEnabled_idx" ON "Invitation"("isEnabled");
